/*
 * This source file was generated by the Gradle 'init' task
 */
package com.orama

import com.orama.client.OramaClient
import com.orama.endpoint.Search
import com.orama.model.search.SearchParams
import kotlinx.serialization.json.JsonPrimitive
import okhttp3.*
import org.mockito.Mockito.mock
import org.mockito.kotlin.any
import org.mockito.kotlin.whenever
import kotlin.test.Test
import kotlin.test.assertEquals

class SearchTest {
    private val exampleSearchResponse = """{"count":1,"elapsed":{"raw":0,"formatted":"0ms"},"hits":[{"id":"233","score":5.787301233651877,"document":{"category":"Cloud","content":"You can install the JavaScript SDK via any major package manager. ","id":"233","path":"/cloud/performing-search/official-sdk#javascript","section":"Performing Search","title":"JavaScript"}}],"facets":{"section":{"count":1,"values":{"Performing Search":1}}}}"""

    private fun exampleSearchParams(): SearchParams {
        return SearchParams.builder(
            term = "red shoes",
            mode = SearchParams.Mode.FULLTEXT
        )
            .limit(10)
            .offset(0)
            .returning(listOf("title", "description"))
            .build()
    }

    @Test fun someLibraryMethodReturnsTrue() {
        val mockHttpClient: OkHttpClient = mock()
        val mockCall: Call = mock()
        val mockResponse: Response = mock()
        val mockResponseBody: ResponseBody = mock()

        val oramaClient = OramaClient(
            apiKey = "anAPIKey",
            endpoint = "https://oramacloud.com/some-endpoint"
        )

        whenever(mockHttpClient.newCall(any())).thenReturn(mockCall)
        whenever(mockResponse.isSuccessful).thenReturn(true)
        whenever(mockResponse.body).thenReturn(mockResponseBody)
        whenever(mockResponseBody.string()).thenReturn(exampleSearchResponse)

        whenever(mockCall.enqueue(any())).thenAnswer {
            invocation ->
            val callback = invocation.arguments[0] as Callback
            callback.onResponse(mockCall, mockResponse)
            null
        }

        Search.get(
            oramaClient,
            mockHttpClient,
            exampleSearchParams(),
        ) { response, error ->
            if (response != null) {
                assertEquals(1, response.count)
                assertEquals(0, response.elapsed.raw)
                assertEquals("0ms", response.elapsed.formatted)

                val hit = response.hits[0]
                assertEquals(5.787301233651877, hit.score)
                assertEquals("233", hit.id)
                assertEquals("Cloud", (hit.document["category"] as? JsonPrimitive)?.content)
                assertEquals("/cloud/performing-search/official-sdk#javascript", (hit.document["path"] as? JsonPrimitive)?.content)
                assertEquals("Performing Search", (hit.document["section"] as? JsonPrimitive)?.content)
                assertEquals("JavaScript", (hit.document["title"] as? JsonPrimitive)?.content)
                assertEquals("You can install the JavaScript SDK via any major package manager. ", (hit.document["content"] as? JsonPrimitive)?.content)
            }
        }
    }
}
